### ISSUE TITLE
我用了您的这个efi在稍作调整后就比较完备了，但是这个声卡我在hackintool里面看不到，是否有同样的情况？受bios影响么？

### ISSUE THREAD

**Issue by zouyanggary** [CrazyHulk/Hackintosh-ASRock-EPC621D8A#2]
在查看了dsdt后只是发现irq补丁需要的三个string名字变了。External (_SB_.PC00.LPC0, DeviceObj)
    External (_SB_.PC00.LPC0.RTC_, DeviceObj)
    External (_SB_.PC00.LPC0.TMR_, DeviceObj)
    External (HPAE, IntObj)，timr变成了tmr，不清楚是否有影响

**Comment by crazyhulk** [comment]
主板声卡默认是 1150， 还有这个不需要 RTC 补丁吧，现在唯一的问题是睡眠后唤醒会重启，还没有解决。
BIOS 中关于声卡的设置是默认设置。

我更新了新的内容，你不一定需要我的 DSDT 等，酌情去除。

**Comment by zouyanggary** [comment]
![image](https://user-images.githubusercontent.com/33047575/88820907-8746a200-d1f4-11ea-8927-73b66bc9f065.png)
![image](https://user-images.githubusercontent.com/33047575/88821008-a80ef780-d1f4-11ea-9d00-f7a663447118.png)
我的声卡就是这么神奇，我的设备显示是？？？，之前一台X79出了这样的问题，能否帮我看看hackintool你的显示是什么

**Comment by zouyanggary** [comment]
我CPU是个至强8175m，96g六通道，这似乎不会影响什么

**Comment by crazyhulk** [comment]
> ![image](https://user-images.githubusercontent.com/33047575/88820907-8746a200-d1f4-11ea-8927-73b66bc9f065.png)
> ![image](https://user-images.githubusercontent.com/33047575/88821008-a80ef780-d1f4-11ea-9d00-f7a663447118.png)
> 我的声卡就是这么神奇，我的设备显示是？？？，之前一台X79出了这样的问题，能否帮我看看hackintool你的显示是什么

你刷提供的 BIOS 了么? 回头提供给你，现在不在身边。

显示问号那个是板载声卡。

**Comment by crazyhulk** [comment]
> 8175m

同为 LGA3647 Skylake-SP 我感觉问题不在这。

**Comment by zouyanggary** [comment]
哦，我已经升级到了10.15.6，目前就是声卡怪异的很。bios 我刷了master里bios文件夹带的那个，所以我们应该是一致的。我准备再刷一次试试看。

**Comment by crazyhulk** [comment]
> 哦，我已经升级到了10.15.6，目前就是声卡怪异的很。bios 我刷了master里bios文件夹带的那个，所以我们应该是一致的。我准备再刷一次试试看。

不必， 你有时间重置下 BIOS。

声卡相关信息:
![image](https://user-images.githubusercontent.com/13976375/88922749-21fdba00-d2a3-11ea-9375-1960c1a3e82d.png)
![image](https://user-images.githubusercontent.com/13976375/88922788-35a92080-d2a3-11ea-9909-667f8e02ec6d.png)

**Comment by zouyanggary** [comment]
已经ok了，问题解决。我重置了bios后，重新用opencore官方下载原版安装正常了。pcbeta的镜像出了莫名的问题。

**Comment by crazyhulk** [comment]
> 已经ok了，问题解决。我重置了bios后，重新用opencore官方下载原版安装正常了。pcbeta的镜像出了莫名的问题。

建议原版镜像，当然需要有一台能用的Mac。

现在你睡眠什么现象？

**Comment by zouyanggary** [comment]
![WechatIMG61](https://user-images.githubusercontent.com/33047575/89003740-270a4a00-d333-11ea-9be0-c30242032a76.png)

**Comment by zouyanggary** [comment]
在接有sata硬盘的时候，无法睡眠，睡眠就唤醒重启。屏蔽掉SATA后睡眠断电，然后重启报错。这个错误看起来是没办法了，似乎是APCI的问题，换用SMC可以尝试一下

**Comment by zouyanggary** [comment]
![WeChatd252306a651f0be024b4f89879d3400c](https://user-images.githubusercontent.com/33047575/89004800-88cbb380-d335-11ea-8761-ffb1498482f9.png)
这个开机前的一串代码我怎么也去不掉，有没有什么方案？

**Comment by chphaeton** [comment]
> ![WeChatd252306a651f0be024b4f89879d3400c](https://user-images.githubusercontent.com/33047575/89004800-88cbb380-d335-11ea-8761-ffb1498482f9.png)
> 这个开机前的一串代码我怎么也去不掉，有没有什么方案？

boot args里面log去掉?

**Comment by crazyhulk** [comment]
> > ![WeChatd252306a651f0be024b4f89879d3400c](https://user-images.githubusercontent.com/33047575/89004800-88cbb380-d335-11ea-8761-ffb1498482f9.png)
> > 这个开机前的一串代码我怎么也去不掉，有没有什么方案？
> 
> boot args里面log去掉?

他应该没有这个问题
