### ISSUE TITLE
我定制了一下applealc的声卡节点。现在睡眠似乎是ACPI的问题，不知道是不是这个解了CFG的bios有问题。我的待机太久似乎会重启。

### ISSUE THREAD

**Issue by zouyanggary** [CrazyHulk/Hackintosh-ASRock-EPC621D8A#3]
可否出现待机一段时间自动重启的情况？

**Comment by crazyhulk** [comment]
睡眠问题是 0x11A 寄存器导致的，该 BIOS 仅解锁了 CFG Lock.

没有碰到待机太久出现重启的问题，是 kernel panic 么？

**Comment by zouyanggary** [comment]
![801596699460_ pic_hd](https://user-images.githubusercontent.com/33047575/89657471-b7322b80-d8ff-11ea-9fe5-a62d8f555043.jpg)
目前看来都是AppleACPIPlatform的报错，无一例外。至于0x11A这个，是否有什么思路？

**Comment by crazyhulk** [comment]
@zouyanggary 需要修改 BIOS ，这个超出了我的能力范围，具体可以看 GitHub 一个项目 UEFIPatch，但是它目前还不适用于 C621. 
自定义节点后麦克风有回音没有？

**Comment by zouyanggary** [comment]
我继续待机，让它测试一下是否会重启。我感觉这个bios像个残次品，但是不解锁cfg似乎睡眠也搞不定？？ ALC1150我定制了5个节点的路径，我测试了一下，好像没有回音，但是我前置的麦克风插口坏了，所以我只能测试4个插孔，根据后置Mac in的路径，前置应该也不会有问题。我可以给你测试一下？我更新了OC0.6，根据APPLEALC1.5.1编译了一个，layoutID=1
[AppleALC.kext.zip](https://github.com/CrazyHulk/Hackintosh-ASRock-EPC621D8A/files/5042135/AppleALC.kext.zip)

**Comment by zouyanggary** [comment]
之前我问你说启动跑代码，是因为OC自带的文件被删了一部分，OC0.6原版从新做的启动EFI就没问题了

**Comment by crazyhulk** [comment]
> 我继续待机，让它测试一下是否会重启。我感觉这个bios像个残次品，但是不解锁cfg似乎睡眠也搞不定？？ ALC1150我定制了5个节点的路径，我测试了一下，好像没有回音，但是我前置的麦克风插口坏了，所以我只能测试4个插孔，根据后置Mac in的路径，前置应该也不会有问题。我可以给你测试一下？我更新了OC0.6，根据APPLEALC1.5.1编译了一个，layoutID=1
> [AppleALC.kext.zip](https://github.com/CrazyHulk/Hackintosh-ASRock-EPC621D8A/files/5042135/AppleALC.kext.zip)

重启大概率是因为自动睡眠了导致的。
确实这两个寄存器会影响睡眠和稳定性，你在 OpenCore 的文档中也可以看到相关说明。

CFG Lock 和 0x11A 寄存器只是在 Mac OS 下有特殊需要，这个 BIOS 的作者当时没考虑 0x11A.
关于 C621 的 Patch  [看这里](https://github.com/LongSoft/UEFITool/issues/192)
需要有人修复 BUG 。

**Comment by crazyhulk** [comment]
> 之前我问你说启动跑代码，是因为OC自带的文件被删了一部分，OC0.6原版从新做的启动EFI就没问题了

我还没有升级 6.0，粗略的看了一下日志，没有发现刚需，加上 11 还没有发布正式版，就没有着急处理。

**Comment by zouyanggary** [comment]
你试一下我的AppleALC，这个oc文件你升级的时候不要删其他没用就没事了。我电源已经启动了关闭屏幕但是不允许睡眠，但是我不知道这样它还能休眠？？

**Comment by crazyhulk** [comment]
> 你试一下我的AppleALC，这个oc文件你升级的时候不要删其他没用就没事了。我电源已经启动了关闭屏幕但是不允许睡眠，但是我不知道这样它还能休眠？？

好的，我测试完毕会更新到 Readme。

讲道理如果你设置不休眠是不能休眠的，你可以截图你的电源设置。
提供一下你的 Config.plist, 如果你有很多变动。

**Comment by zouyanggary** [comment]
![image](https://user-images.githubusercontent.com/33047575/89661705-9967c500-d905-11ea-8e9a-1f9f8c7b1232.png)
config上没有什么大改动，改用了virtualSMC和HWmonitorSMC2监控状态。我使用hacktintool查看msr状态，只要点了就重启

**Comment by zouyanggary** [comment]
此外，nvmefix1.03不要升级，这个会直接导致系统kenel panic，原因未知。这个坑了我一晚上

**Comment by crazyhulk** [comment]
> ![image](https://user-images.githubusercontent.com/33047575/89661705-9967c500-d905-11ea-8e9a-1f9f8c7b1232.png)
> config上没有什么大改动，改用了virtualSMC和HWmonitorSMC2监控状态。我使用hacktintool查看msr状态，只要点了就重启

重启就是因为寄存器的原因，这个暂时只能等 Patch BIOS。
你这里显示了 Processor，我处理器压根不显示。

能显示 CPU 风扇么？

看你的电源设置，貌似没有问题。
但是睡眠模式是0，这个有点奇怪，不知道是不是你故意的。

**Comment by crazyhulk** [comment]
> 此外，nvmefix1.03不要升级，这个会直接导致系统kenel panic，原因未知。这个坑了我一晚上

我把 NVMeFix 移除了，有没有它我启动都很慢，而且貌似它并不能解决我的 P4500 固态问题。

**Comment by zouyanggary** [comment]
这个cpu风扇是不会显示的。它的风扇控制都是被集成到bmc通过IPMI来看得，所以看不到风扇不用纠结。在bios里有个设置关于传感器的，默认auto就是这样，要么就手动设置，我没有常识。你说你不显示处理器型号？可能我是二十四核模拟的board-ID正好是的。但是我这样CPU满载睿频只有2.8,windows下是3.1性能低了10%。

**Comment by zouyanggary** [comment]
> > 此外，nvmefix1.03不要升级，这个会直接导致系统kenel panic，原因未知。这个坑了我一晚上
> 
> 我把 NVMeFix 移除了，有没有它我启动都很慢，而且貌似它并不能解决我的 P4500 固态问题。
我启动的时候，从读完主板的logo，全屏黑了，出现苹果图标到读条完进入系统，大概是7到10秒，比windows快多了

**Comment by zouyanggary** [comment]
![image](https://user-images.githubusercontent.com/33047575/89663514-3d527000-d908-11ea-8d17-ff7461921675.png)
这个监控效果很厉害

**Comment by crazyhulk** [comment]
> 这个cpu风扇是不会显示的。它的风扇控制都是被集成到bmc通过IPMI来看得，所以看不到风扇不用纠结。在bios里有个设置关于传感器的，默认auto就是这样，要么就手动设置，我没有常识。你说你不显示处理器型号？可能我是二十四核模拟的board-ID正好是的。但是我这样CPU满载睿频只有2.8,windows下是3.1性能低了10%。

我的睿频倒是没有什么问题，跟 board-ID 会有关系么？感觉这个性能问题不应该, 我看你电源管理也加载了，你是不是用了我的 ssdt？
现在用 LGA3647 Cascade 应该只有 MacPro7,1 ，没找到原因为啥不显示处理器名字。

**Comment by crazyhulk** [comment]
> > > 此外，nvmefix1.03不要升级，这个会直接导致系统kenel panic，原因未知。这个坑了我一晚上
> > 
> > 
> > 我把 NVMeFix 移除了，有没有它我启动都很慢，而且貌似它并不能解决我的 P4500 固态问题。
> > 我启动的时候，从读完主板的logo，全屏黑了，出现苹果图标到读条完进入系统，大概是7到10秒，比windows快多了

我的要 20s +，里面有个 NVMe 报错，我没有 SATA 硬盘。

**Comment by zouyanggary** [comment]
> > 这个cpu风扇是不会显示的。它的风扇控制都是被集成到bmc通过IPMI来看得，所以看不到风扇不用纠结。在bios里有个设置关于传感器的，默认auto就是这样，要么就手动设置，我没有常识。你说你不显示处理器型号？可能我是二十四核模拟的board-ID正好是的。但是我这样CPU满载睿频只有2.8,windows下是3.1性能低了10%。
> 
> 我的睿频倒是没有什么问题，跟 board-ID 会有关系么？感觉这个性能问题不应该, 我看你电源管理也加载了，你是不是用了我的 ssdt？
> 现在用 LGA3647 Cascade 应该只有 MacPro7,1 ，没找到原因为啥不显示处理器名字。

![image](https://user-images.githubusercontent.com/33047575/89699693-22f5b200-d95b-11ea-9a25-6d72469084b6.png)
如果不显示名字，很大程度上是board-id影响显示，不过可以手动改CPU名字，cpufriend可以帮助选定board-id。我是用了你的SSDT，但是哪个ssdt定义了频率的？processor？

**Comment by crazyhulk** [comment]
> > > 这个cpu风扇是不会显示的。它的风扇控制都是被集成到bmc通过IPMI来看得，所以看不到风扇不用纠结。在bios里有个设置关于传感器的，默认auto就是这样，要么就手动设置，我没有常识。你说你不显示处理器型号？可能我是二十四核模拟的board-ID正好是的。但是我这样CPU满载睿频只有2.8,windows下是3.1性能低了10%。
> > 
> > 
> > 我的睿频倒是没有什么问题，跟 board-ID 会有关系么？感觉这个性能问题不应该, 我看你电源管理也加载了，你是不是用了我的 ssdt？
> > 现在用 LGA3647 Cascade 应该只有 MacPro7,1 ，没找到原因为啥不显示处理器名字。
> 
> ![image](https://user-images.githubusercontent.com/33047575/89699693-22f5b200-d95b-11ea-9a25-6d72469084b6.png)
> 如果不显示名字，很大程度上是board-id影响显示，不过可以手动改CPU名字，cpufriend可以帮助选定board-id。我是用了你的SSDT，但是哪个ssdt定义了频率的？processor？

对，Processor 你需要自己定制一下，我用 CPUFriendFriend 时没有那么多选项, 默认用的也是 MacPro 的 board-id.

**Comment by crazyhulk** [comment]
> 我继续待机，让它测试一下是否会重启。我感觉这个bios像个残次品，但是不解锁cfg似乎睡眠也搞不定？？ ALC1150我定制了5个节点的路径，我测试了一下，好像没有回音，但是我前置的麦克风插口坏了，所以我只能测试4个插孔，根据后置Mac in的路径，前置应该也不会有问题。我可以给你测试一下？我更新了OC0.6，根据APPLEALC1.5.1编译了一个，layoutID=1
> [AppleALC.kext.zip](https://github.com/CrazyHulk/Hackintosh-ASRock-EPC621D8A/files/5042135/AppleALC.kext.zip)

貌似不太行，没有输出设备。

**Comment by zouyanggary** [comment]
> > 我继续待机，让它测试一下是否会重启。我感觉这个bios像个残次品，但是不解锁cfg似乎睡眠也搞不定？？ ALC1150我定制了5个节点的路径，我测试了一下，好像没有回音，但是我前置的麦克风插口坏了，所以我只能测试4个插孔，根据后置Mac in的路径，前置应该也不会有问题。我可以给你测试一下？我更新了OC0.6，根据APPLEALC1.5.1编译了一个，layoutID=1
> > [AppleALC.kext.zip](https://github.com/CrazyHulk/Hackintosh-ASRock-EPC621D8A/files/5042135/AppleALC.kext.zip)
> 
> 貌似不太行，没有输出设备。

忘了。这个是给予1.5.1编译的，也即是基于LILU1.4.6。我找个1.5的给你吧

**Comment by crazyhulk** [comment]
> > > 我继续待机，让它测试一下是否会重启。我感觉这个bios像个残次品，但是不解锁cfg似乎睡眠也搞不定？？ ALC1150我定制了5个节点的路径，我测试了一下，好像没有回音，但是我前置的麦克风插口坏了，所以我只能测试4个插孔，根据后置Mac in的路径，前置应该也不会有问题。我可以给你测试一下？我更新了OC0.6，根据APPLEALC1.5.1编译了一个，layoutID=1
> > > [AppleALC.kext.zip](https://github.com/CrazyHulk/Hackintosh-ASRock-EPC621D8A/files/5042135/AppleALC.kext.zip)
> > 
> > 
> > 貌似不太行，没有输出设备。
> 
> 忘了。这个是给予1.5.1编译的，也即是基于LILU1.4.6。我找个1.5的给你吧

那我更新一下 lilu 就行了。我已经升级到 oc0.6

**Comment by zouyanggary** [comment]
> > > > 这个cpu风扇是不会显示的。它的风扇控制都是被集成到bmc通过IPMI来看得，所以看不到风扇不用纠结。在bios里有个设置关于传感器的，默认auto就是这样，要么就手动设置，我没有常识。你说你不显示处理器型号？可能我是二十四核模拟的board-ID正好是的。但是我这样CPU满载睿频只有2.8,windows下是3.1性能低了10%。
> > > 
> > > 
> > > 我的睿频倒是没有什么问题，跟 board-ID 会有关系么？感觉这个性能问题不应该, 我看你电源管理也加载了，你是不是用了我的 ssdt？
> > > 现在用 LGA3647 Cascade 应该只有 MacPro7,1 ，没找到原因为啥不显示处理器名字。
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/33047575/89699693-22f5b200-d95b-11ea-9a25-6d72469084b6.png)
> > 如果不显示名字，很大程度上是board-id影响显示，不过可以手动改CPU名字，cpufriend可以帮助选定board-id。我是用了你的SSDT，但是哪个ssdt定义了频率的？processor？
> 
> 对，Processor 你需要自己定制一下，我用 CPUFriendFriend 时没有那么多选项, 默认用的也是 MacPro 的 board-id.

![image](https://user-images.githubusercontent.com/33047575/89701344-9a7e0e00-d968-11ea-9d6e-7deced2111ff.png)
我没找到processor定义频率的地方

**Comment by zouyanggary** [comment]
![image](https://user-images.githubusercontent.com/33047575/89701885-dff10a00-d96d-11ea-8226-9a1628d83c4f.png)
这是CPU的睿频信息，最低12X，默认25X，都是 正确的，但是睿频这些都达不到，最高35X没出现，满载31X也不会，次年本次HR测试只会卡在2.8GHZ。你的CPU我查了，6298R满载也不是2.8啊好像

**Comment by crazyhulk** [comment]
> ![image](https://user-images.githubusercontent.com/33047575/89701885-dff10a00-d96d-11ea-8226-9a1628d83c4f.png)
> 这是CPU的睿频信息，最低12X，默认25X，都是 正确的，但是睿频这些都达不到，最高35X没出现，满载31X也不会，次年本次HR测试只会卡在2.8GHZ。你的CPU我查了，6298R满载也不是2.8啊好像

我的是 6278，  base 2.6 睿频 3.3 tubor 3.5 目前来看正常。
![image](https://user-images.githubusercontent.com/13976375/89703443-58ab9280-d97d-11ea-9c89-700a017ad503.png)

你可以提供下你的 dsdt

**Comment by crazyhulk** [comment]
> 新一下 lilu 就行了。我已经升级到 oc0.6

试了一下，输出可以，我的麦克风回音应该是 USB 麦的原因。

**Comment by zouyanggary** [comment]
我用的就是你的DSDT。我用自己的dsdt会死机，但是我不知道你的dsdt里该了频率啊。这个声卡麦克风我用macin录入和linein录入都没问题。要不你帮我修正一个dsdt频率发给我试试？base 2.5 全核满载 3.1 睿频最高3.5

**Comment by zouyanggary** [comment]
intel的这个频率变频我的也能看到3.5最高，但是用cinbench R20 跑一下渲染就出来了，最高2.8

**Comment by zouyanggary** [comment]
> > 新一下 lilu 就行了。我已经升级到 oc0.6
> 
> 试了一下，输出可以，我的麦克风回音应该是 USB 麦的原因。

APPLEALC自带的节点都不能正常保证后置和前耳机同时正常使用，这个到时候换个layout贡献给applealc

**Comment by crazyhulk** [comment]
> intel的这个频率变频我的也能看到3.5最高，但是用cinbench R20 跑一下渲染就出来了，最高2.8

全核都跑不满的。
我现在没有用 dsdt，只用了 ssdt 补丁。
你可以留个即时通讯工具（微信）。

**Comment by zouyanggary** [comment]
> > intel的这个频率变频我的也能看到3.5最高，但是用cinbench R20 跑一下渲染就出来了，最高2.8
> 
> 全核都跑不满的。
> 我现在没有用 dsdt，只用了 ssdt 补丁。
> 你可以留个即时通讯工具（微信），这样太慢了。

加我微信吧：zouyanggary。它肯定跑不满，但是理论上它不该和windows有差距啊

**Comment by rickliu2000** [comment]
要不要拉个交流群啊，网上c621的黑苹果资源好像很少的样子，国内外都是一样。

**Comment by rickliu2000** [comment]
你的ssdt-processor.aml是怎么生成的？是用processor friendfriend还是在linux/windows下获取本机的dsdt然后修改啊
我的关于本机里也是只显示频率，没有型号

**Comment by crazyhulk** [comment]
> 你的ssdt-processor.aml是怎么生成的？是用processor friendfriend还是在linux/windows下获取本机的dsdt然后修改啊
> 我的关于本机里也是只显示频率，没有型号

自修改，他并不解决型号或者频率问题，他是为了解决附件提供的 BIOS 无法引导的问题。
