### ISSUE TITLE
能否提供10.13.6~10.14.6的EFI？

### ISSUE THREAD

**Issue by lgq163** [CrazyHulk/Hackintosh-ASRock-EPC621D8A#5]
我与您主板相同，CPU 8175M，显卡Vega 64，稍加调整即能用于10.15--11.1安装和升级；10.13.6能安装，但USB键鼠卡顿，不认U盘；10.14.6安装卡waiting for boot device，网上查找的几个办法都未能解决问题。能否麻烦您调试提供10.13.6--10.14.6的EFI？非常感谢

**Comment by crazyhulk** [comment]
不知道为什么要低版本的处理，我这边没有测试硬盘了，不方便帮你 调试

建议你用旧版 bios ，然后选 clover 引导 10.13.

**Comment by lgq163** [comment]
好的，谢谢你的建议。
